apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-db
  name: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - image: registry.redhat.io/rhel8/postgresql-13
        name: postgresql-13        
        env:
          - name: POSTGRESQL_USER
            value: todo_user
          - name: POSTGRESQL_PASSWORD
            value: todo_pass
          - name: POSTGRESQL_DATABASE
            value: todo
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-claim


