apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: todo-app-template
  annotations:
    description: "Deploys the Todo App (Quay Images) + Postgres DB"
    tags: "python,nginx,postgresql,todo"
objects:
# 1. Database Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: todo-db
  spec:
    selector:
      matchLabels:
        app: todo-db
    template:
      metadata:
        labels:
          app: todo-db
      spec:
        containers:
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-13
          env:
          - name: POSTGRESQL_USER
            value: "${DB_USER}"
          - name: POSTGRESQL_PASSWORD
            value: "${DB_PASSWORD}"
          - name: POSTGRESQL_DATABASE
            value: "${DB_NAME}"
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: db-data
        volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-claim

# 2. Database Service
- apiVersion: v1
  kind: Service
  metadata:
    name: todo-db
  spec:
    ports:
    - port: 5432
    selector:
      app: todo-db

# 3. DB PVC (Storage)
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: db-data-claim
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi

# 4. Backend Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: todo-backend
  spec:
    selector:
      matchLabels:
        app: todo-backend
    template:
      metadata:
        labels:
          app: todo-backend
      spec:
        containers:
        - name: backend
          image: "${BACKEND_IMAGE}"
          ports:
          - containerPort: 8080
          env:
          - name: DATABASE_URL
            value: "postgresql://${DB_USER}:${DB_PASSWORD}@todo-db:5432/${DB_NAME}"

# 5. Backend Service
- apiVersion: v1
  kind: Service
  metadata:
    name: todo-backend
  spec:
    ports:
    - port: 8080
    selector:
      app: todo-backend

# 6. Frontend Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: todo-frontend
  spec:
    selector:
      matchLabels:
        app: todo-frontend
    template:
      metadata:
        labels:
          app: todo-frontend
      spec:
        containers:
        - name: frontend
          image: "${FRONTEND_IMAGE}"
          ports:
          - containerPort: 8080

# 7. Frontend Service & Route
- apiVersion: v1
  kind: Service
  metadata:
    name: todo-frontend
  spec:
    ports:
    - port: 8080
    selector:
      app: todo-frontend
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: todo-frontend
  spec:
    to:
      kind: Service
      name: todo-frontend
    port:
      targetPort: 8080

# --- PARAMETERS SECTION ---
parameters:
- name: DB_USER
  description: "Database Username"
  value: "todo_user"
- name: DB_PASSWORD
  description: "Database Password"
  generate: expression
  from: "[a-zA-Z0-9]{8}"
- name: DB_NAME
  description: "Database Name"
  value: "todo"
- name: BACKEND_IMAGE
  description: "Quay URL for Backend"
  required: true
- name: FRONTEND_IMAGE
  description: "Quay URL for Frontend"
  required: true
