apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-backend
  name: todo-backend
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-backend
  type: ClusterIP
status:
  loadBalancer: {}
